campuses:
  East:
    counties:
      [Dearborn, Decatur, Fayette, Franklin, Henry, Ohio, Randolph, Ripley, Rush, Union, Wayne]
    colors: "#990000"
  Indianapolis:
    counties:
      [Boone, Brown, Hamilton, Hancock, Hendricks, Johnson, Marion, Morgan, Shelby]
    colors: "#7A0000"
  Columbus:
    counties:
      [Bartholomew, Decatur, Jackson, Jennings, Ripley]
    colors: "#EEEDEB"
    colors: "#EEEDEB"
  Fort Wayne:
    counties:
      [Adams, Allen, De Kalb, Huntington, LaGrange, Noble, Steuben, Wells, Whitley]
    colors: "#4A4A4A"
  Kokomo:
    counties:
      [Carroll, Cass, Clinton, Fulton, Grant, Howard, Miami, Tipton, Wabash]
    colors: "#F0B323"
  Northwest:
    counties:
      [Jasper, Lake, LaPorte, Newton, Porter]
    colors: "#2C3E73"
  South Bend:
    counties:
      [Elkhart, Fulton, Kosciusko, LaGrange, Marshall, Starke, St. Joseph]
    colors: "#007377"
  South East:
    counties:
      [Clark, Crawford, Floyd, Harrison, Jefferson, Ohio, Scott, Switzerland, Washington]
    colors: "#1F6F43"
  Bloomington:
    counties:
      [Adams, Allen, Bartholomew, Benton, Blackford, Boone, Brown, Carroll, Cass, Clark, Clay, Clinton, Crawford, Daviess, Dearborn, Decatur, DeKalb, Delaware, Dubois, Elkhart, 
      Fayette, Floyd, Fountain, Franklin, Fulton, Gibson, Grant, Greene, Hamilton, Hancock, Harrison, Hendricks, Henry, Howard, Huntington, Jackson, Jasper, Jay, Jefferson, 
      Jennings, Johnson, Knox, Kosciusko, LaGrange, Lake, La Porte, Lawrence, Madison, Marion, Marshall, Martin, Miami, Monroe, Montgomery, Morgan, Newton, Noble, Ohio, 
      Orange, Owen, Parke, Perry, Pike, Porter, Posey, Pulaski, Putnam, Randolph, Ripley, Rush, Scott, Shelby, Spencer, St Joseph, Starke, Steuben, Sullivan, Switzerland, Tippecanoe, 
      Tipton, Union, Vanderburgh, Vermillion, Vigo, Wabash, Warren, Warrick, Washington, Wayne, Wells, White, Whitley, De Kalb]
    colors: "#522D80"
